services:
  db-dev:
    image: 'postgres:17.4-alpine3.21'
    ports:
      - '5432:5432'
    env_file:
      - .env.development
    volumes:
      - pg_data:/var/lib/postgresql/data

  db-test:
    image: 'postgres:17.4-alpine3.21'
    ports:
      - '5432:5432'
    env_file:
      - .env.test

  redis:
    image: 'redis:7.4.3-alpine'
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --save 20 1 --loglevel warning

volumes:
  pg_data:
  redis_data:
