services:
  db-dev:
    image: 'postgres:17.4-alpine3.21'
    ports:
      - '5432:5432'
    env_file:
      - .env.development
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
