services:
  db-dev:
    image: 'postgres:17.4-alpine3.21'
    ports:
      - '5432:5432'
    env_file:
      - .env.development
    volumes:
      - pg_data:/var/lib/postgresql/data

  db-test:
    image: 'postgres:17.4-alpine3.21'
    ports:
      - '5432:5432'
    env_file:
      - .env.test
  
  api:
    build:
      context: ./api
    env_file:
      - ./api/.env.development 
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db-dev 
    
  worker:
    build:
      context: ./worker
    env_file:
      - ./worker/.env.development 
    ports:
      - "9000:9000"
    depends_on:
      - db-dev 

volumes:
  pg_data:
